/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.openintents.applications.splashplay;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int bluetooth_icon1=0x7f020000;
        public static final int bluetooth_icon1_small_16=0x7f020001;
        public static final int fret001a=0x7f020002;
        public static final int icon=0x7f020003;
        public static final int marker001a=0x7f020004;
        public static final int nut001a=0x7f020005;
        public static final int shiny_button_pause=0x7f020006;
        public static final int shiny_button_pause_1=0x7f020007;
        public static final int shiny_button_pause_selected=0x7f020008;
        public static final int shiny_button_play=0x7f020009;
        public static final int shiny_button_play_1=0x7f02000a;
        public static final int shiny_button_play_selected=0x7f02000b;
        public static final int shiny_button_reset=0x7f02000c;
        public static final int shiny_button_reset_1=0x7f02000d;
        public static final int shiny_button_reset_selected=0x7f02000e;
        public static final int shiny_button_stop=0x7f02000f;
        public static final int shiny_button_stop_1=0x7f020010;
        public static final int shiny_button_stop_selected=0x7f020011;
        public static final int shiny_panel_background_001a=0x7f020012;
        public static final int shiny_slider_background001c=0x7f020013;
        public static final int shiny_slider_knob001a=0x7f020014;
        public static final int splashplay_application001a=0x7f020015;
        public static final int splashpod1=0x7f020016;
        public static final int spot001a=0x7f020017;
        public static final int wood001a=0x7f020018;
    }
    public static final class id {
        public static final int chords=0x7f050004;
        public static final int connect=0x7f050001;
        public static final int disconnect=0x7f050002;
        public static final int fretboard=0x7f050005;
        public static final int layout=0x7f050003;
        public static final int pause=0x7f050009;
        public static final int play=0x7f050008;
        public static final int position=0x7f050007;
        public static final int reset=0x7f05000b;
        public static final int slider=0x7f050006;
        public static final int splashpod=0x7f050000;
        public static final int stop=0x7f05000a;
    }
    public static final class layout {
        public static final int bluetooth=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class string {
        public static final int about=0x7f040001;
        public static final int app_name=0x7f040000;
        public static final int bluetooth=0x7f040003;
        public static final int connect=0x7f040004;
        public static final int connect_bluetooth=0x7f040002;
        public static final int splashpod_content=0x7f040005;
    }
}
