/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.openintents.applications.splashplay;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int about001a=0x7f020000;
        public static final int bluetooth_classic_16=0x7f020001;
        public static final int bluetooth_icon1=0x7f020002;
        public static final int bluetooth_icon1_small_16=0x7f020003;
        public static final int bluetooth_icon2_32=0x7f020004;
        public static final int bluetooth_icon2_48=0x7f020005;
        public static final int fret001a=0x7f020006;
        public static final int icon=0x7f020007;
        public static final int marker001a=0x7f020008;
        public static final int nut001a=0x7f020009;
        public static final int nut002a=0x7f02000a;
        public static final int overview_5=0x7f02000b;
        public static final int overview_5_checkbox=0x7f02000c;
        public static final int overview_5_checkbox_checked=0x7f02000d;
        public static final int overview_5_checkbox_checked_1=0x7f02000e;
        public static final int overview_5_checkbox_checked_selected=0x7f02000f;
        public static final int overview_5_checkbox_unchecked=0x7f020010;
        public static final int overview_5_checkbox_unchecked_selected=0x7f020011;
        public static final int overview_5_continue_button=0x7f020012;
        public static final int overview_5_continue_button_normal=0x7f020013;
        public static final int overview_5_continue_button_selected=0x7f020014;
        public static final int overview_5_exit_button=0x7f020015;
        public static final int overview_5_exit_button_normal=0x7f020016;
        public static final int overview_5_exit_button_selected=0x7f020017;
        public static final int shiny_button_pause=0x7f020018;
        public static final int shiny_button_pause_1=0x7f020019;
        public static final int shiny_button_pause_selected=0x7f02001a;
        public static final int shiny_button_play=0x7f02001b;
        public static final int shiny_button_play_1=0x7f02001c;
        public static final int shiny_button_play_selected=0x7f02001d;
        public static final int shiny_button_reset=0x7f02001e;
        public static final int shiny_button_reset_1=0x7f02001f;
        public static final int shiny_button_reset_selected=0x7f020020;
        public static final int shiny_button_stop=0x7f020021;
        public static final int shiny_button_stop_1=0x7f020022;
        public static final int shiny_button_stop_selected=0x7f020023;
        public static final int shiny_panel_background_001a=0x7f020024;
        public static final int shiny_slider_background001c=0x7f020025;
        public static final int shiny_slider_knob001a=0x7f020026;
        public static final int splashplay_application001a=0x7f020027;
        public static final int splashpod1=0x7f020028;
        public static final int spot001a=0x7f020029;
        public static final int spot_void001a=0x7f02002a;
        public static final int wood001a=0x7f02002b;
    }
    public static final class id {
        public static final int chords=0x7f050005;
        public static final int connect=0x7f050001;
        public static final int container=0x7f050003;
        public static final int disconnect=0x7f050002;
        public static final int fretboard=0x7f050006;
        public static final int intro_checkbox=0x7f05000f;
        public static final int intro_continue=0x7f050011;
        public static final int intro_exit=0x7f050010;
        public static final int intro_image=0x7f05000e;
        public static final int introscreen=0x7f05000d;
        public static final int layout=0x7f050004;
        public static final int pause=0x7f05000a;
        public static final int play=0x7f050009;
        public static final int position=0x7f050008;
        public static final int reset=0x7f05000c;
        public static final int slider=0x7f050007;
        public static final int splashpod=0x7f050000;
        public static final int stop=0x7f05000b;
    }
    public static final class layout {
        public static final int bluetooth=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class string {
        public static final int about=0x7f040001;
        public static final int app_name=0x7f040000;
        public static final int bluetooth=0x7f040003;
        public static final int connect=0x7f040004;
        public static final int connect_bluetooth=0x7f040002;
        public static final int splashpod_content=0x7f040005;
    }
}
