/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.openintents.shopping;

public final class Manifest {
    public static final class permission {
        public static final String READ_PERMISSION="org.openintents.shopping.READ_PERMISSION";
        public static final String WRITE_PERMISSION="org.openintents.shopping.WRITE_PERMISSION";
    }
}
