/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.openintents.updatechecker;

public final class Manifest {
    public static final class permission {
        public static final String READ_UPDATE_INFO="org.openintents.updatechecker.READ_UPDATE_INFO";
        public static final String WRITE_UPDATE_INFO="org.openintents.updatechecker.WRITE_UPDATE_INFO";
    }
}
