/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.openintents;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int openintents_icon=0x7f020000;
    }
    public static final class id {
        public static final int latitude=0x7f050000;
        public static final int locations=0x7f050002;
        public static final int longitude=0x7f050001;
    }
    public static final class layout {
        public static final int location_row=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class string {
        public static final int add_current_location=0x7f040001;
        public static final int app_name=0x7f040000;
    }
}
