/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.openintents.samples.presentpicker;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int about001a=0x7f020000;
        public static final int ball=0x7f020001;
        public static final int bike=0x7f020002;
        public static final int book=0x7f020003;
        public static final int boy_1=0x7f020004;
        public static final int boy_3=0x7f020005;
        public static final int boy_6=0x7f020006;
        public static final int bubbleframe_lightorange=0x7f020007;
        public static final int car=0x7f020008;
        public static final int cat=0x7f020009;
        public static final int cd=0x7f02000a;
        public static final int cup=0x7f02000b;
        public static final int dog=0x7f02000c;
        public static final int fasticon_banner=0x7f02000d;
        public static final int flashlight=0x7f02000e;
        public static final int flower=0x7f02000f;
        public static final int frame_lightorange=0x7f020010;
        public static final int frame_orange=0x7f020011;
        public static final int gift=0x7f020012;
        public static final int girl_1=0x7f020013;
        public static final int girl_3=0x7f020014;
        public static final int girl_5=0x7f020015;
        public static final int ice_cream=0x7f020016;
        public static final int joystick=0x7f020017;
        public static final int picture=0x7f020018;
        public static final int pipe=0x7f020019;
        public static final int present001b=0x7f02001a;
        public static final int present_application001a=0x7f02001b;
        public static final int roller=0x7f02001c;
        public static final int shoppinglist001b=0x7f02001d;
        public static final int shoppinglistadditem002a=0x7f02001e;
        public static final int skate=0x7f02001f;
        public static final int toy=0x7f020020;
    }
    public static final class id {
        public static final int age=0x7f050009;
        public static final int button_add=0x7f050010;
        public static final int button_view=0x7f050011;
        public static final int content1=0x7f050003;
        public static final int content2=0x7f05000d;
        public static final int fasticon=0x7f050000;
        public static final int image=0x7f050004;
        public static final int name=0x7f050005;
        public static final int occasion=0x7f05000b;
        public static final int ok=0x7f050001;
        public static final int personality=0x7f05000a;
        public static final int radio_f=0x7f050008;
        public static final int radio_m=0x7f050007;
        public static final int radio_mf=0x7f050006;
        public static final int results=0x7f05000e;
        public static final int search=0x7f05000c;
        public static final int selection=0x7f05000f;
        public static final int tabhost=0x7f050002;
    }
    public static final class layout {
        public static final int presentpicker_about=0x7f030000;
        public static final int presentpicker_main=0x7f030001;
    }
    public static final class string {
        /**  Strings that are also in core 
         */
        public static final int about=0x7f040015;
        public static final int about_content=0x7f040010;
        public static final int about_icons=0x7f040012;
        public static final int about_title=0x7f04000f;
        public static final int add_item_to=0x7f040004;
        public static final int age=0x7f040008;
        public static final int autocomplete_hint=0x7f04000e;
        public static final int copyright=0x7f040011;
        public static final int female=0x7f040007;
        public static final int item_added_to_shopping=0x7f040013;
        public static final int item_not_added_to_shopping=0x7f040014;
        public static final int male=0x7f040006;
        public static final int name=0x7f040002;
        public static final int occasion=0x7f04000a;
        public static final int ok=0x7f040016;
        public static final int personality=0x7f040009;
        public static final int pick_contact=0x7f040001;
        public static final int presentpicker_app_name=0x7f040000;
        public static final int recommendation=0x7f040003;
        public static final int search=0x7f04000b;
        public static final int selection=0x7f04000c;
        public static final int selection_hint=0x7f04000d;
        public static final int view_shopping_list=0x7f040005;
    }
}
