/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.openintents.samples.apidemossensors;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int app_sample_code_sensors=0x7f020000;
        public static final int mobile_shake001a=0x7f020001;
        public static final int mobile_shake_settings001a=0x7f020002;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
    }
}
