/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.openintents.bcinfo;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int browse_button=0x7f050003;
        public static final int cipher=0x7f05000c;
        public static final int compare_button=0x7f050004;
        public static final int file_path=0x7f050002;
        public static final int header=0x7f05000a;
        public static final int info=0x7f050001;
        public static final int keyagreement=0x7f05000e;
        public static final int keyfactory=0x7f050010;
        public static final int keystore=0x7f050012;
        public static final int label_cipher=0x7f05000b;
        public static final int label_keyagreement=0x7f05000d;
        public static final int label_keyfactory=0x7f05000f;
        public static final int label_keystore=0x7f050011;
        public static final int label_messagedigest=0x7f050013;
        public static final int label_service_types=0x7f050008;
        public static final int lbl_comparison=0x7f050000;
        public static final int messagedigest=0x7f050014;
        public static final int name=0x7f050006;
        public static final int results=0x7f050005;
        public static final int service_types=0x7f050009;
        public static final int version=0x7f050007;
    }
    public static final class layout {
        public static final int encryptcompare=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int compare_progress=0x7f040005;
        public static final int menu_compare=0x7f040001;
        public static final int no_filemanager_installed=0x7f040002;
        public static final int open_button=0x7f040004;
        public static final int open_title=0x7f040003;
    }
}
