/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.openintents.samples.openglsensors;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int icon_openintents_sample=0x7f020001;
        public static final int mobile_shake001a=0x7f020002;
        public static final int mobile_shake_settings001a=0x7f020003;
        public static final int openglsensors_application001a=0x7f020004;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int accelerometer=0x7f040005;
        public static final int accelerometer_compass=0x7f040008;
        public static final int app_name=0x7f040000;
        public static final int compass=0x7f040007;
        public static final int connect_simulator=0x7f040002;
        public static final int not_available=0x7f040006;
        public static final int orientation=0x7f040009;
        public static final int orientation_compass=0x7f04000a;
        public static final int sensor=0x7f040003;
        public static final int sensor_type=0x7f040004;
        public static final int settings=0x7f040001;
    }
}
