/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.openintents.applications.newsreader;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int addfeed=0x7f020000;
        public static final int delfeed=0x7f020001;
        public static final int feedsettings=0x7f020002;
        public static final int icon=0x7f020003;
        public static final int newfeed=0x7f020004;
        public static final int news_application001a=0x7f020005;
        public static final int openintents_icon=0x7f020006;
        public static final int settings001a=0x7f020007;
        public static final int shoppinglistdelete001b=0x7f020008;
        public static final int tagging_application001a=0x7f020009;
        public static final int tagging_magnolia_application001a=0x7f02000a;
    }
    public static final class id {
        public static final int CancelFeedSettings=0x7f050008;
        public static final int afeedsettings_feedtype=0x7f050004;
        public static final int afeedsettings_ft1=0x7f050000;
        public static final int afeedsettings_ft2=0x7f050003;
        public static final int afeedsettings_ft3=0x7f050006;
        public static final int afeedsettings_updatecycle=0x7f050005;
        public static final int feedname=0x7f050002;
        public static final int feedurl=0x7f050001;
        public static final int newsmessage_items_link=0x7f05000b;
        public static final int newsmessage_items_message=0x7f05000a;
        public static final int newsmessage_items_title=0x7f050009;
        public static final int newsreader_atomlistitems=0x7f05000d;
        public static final int newsreader_feedrow_feedname=0x7f05000e;
        public static final int newsreader_listitems=0x7f05000c;
        public static final int saveFeedSettings=0x7f050007;
        public static final int servicesettings_cancel=0x7f050012;
        public static final int servicesettings_save=0x7f050011;
        public static final int startFeedService=0x7f05000f;
        public static final int stopFeedService=0x7f050010;
    }
    public static final class layout {
        public static final int afeedsettings=0x7f030000;
        public static final int main=0x7f030001;
        public static final int newsmessage_items=0x7f030002;
        public static final int newsmessage_row=0x7f030003;
        public static final int newsreader=0x7f030004;
        public static final int newsreader_feedrow=0x7f030005;
        public static final int servicesettings=0x7f030006;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
