/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.openintents.filemanager;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_launcher_folder=0x7f020000;
        public static final int ic_launcher_folder_open=0x7f020001;
        public static final int ic_launcher_home=0x7f020002;
        public static final int icon_file=0x7f020003;
    }
    public static final class id {
        public static final int button_pick=0x7f060001;
        public static final int filename=0x7f060000;
        public static final int icon=0x7f060002;
        public static final int info=0x7f060004;
        public static final int text=0x7f060003;
    }
    public static final class layout {
        public static final int filelist=0x7f030000;
        public static final int filelist_item=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int application_not_available=0x7f050007;
        public static final int current_dir=0x7f050006;
        public static final int dirname_app_name=0x7f050001;
        public static final int dirnameinput_cmd_return=0x7f050003;
        public static final int dirnameinput_hint=0x7f050004;
        public static final int menu_new_folder=0x7f050002;
        public static final int up_one_level=0x7f050005;
    }
    public static final class xml {
        public static final int mimetypes=0x7f040000;
    }
}
