/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.openintents.filemanager;

public final class R {
    public static final class array {
        public static final int fileEndingAudio=0x7f040001;
        public static final int fileEndingImage=0x7f040000;
        public static final int fileEndingPackage=0x7f040002;
        public static final int fileEndingWebText=0x7f040003;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int audio=0x7f020000;
        public static final int folder=0x7f020001;
        public static final int goroot=0x7f020002;
        public static final int icon=0x7f020003;
        public static final int image=0x7f020004;
        public static final int packed=0x7f020005;
        public static final int text=0x7f020006;
        public static final int uponelevel=0x7f020007;
        public static final int webtext=0x7f020008;
    }
    public static final class layout {
        public static final int file_row=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int current_dir=0x7f050006;
        public static final int dirname_app_name=0x7f050001;
        public static final int dirnameinput_cmd_return=0x7f050003;
        public static final int dirnameinput_hint=0x7f050004;
        public static final int menu_new_folder=0x7f050002;
        public static final int up_one_level=0x7f050005;
    }
}
