/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.openintents;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int openintents_icon=0x7f020000;
        public static final int shoppinglist01d=0x7f020001;
        public static final int strikethrough=0x7f020002;
    }
    public static final class id {
        public static final int about=0x7f050009;
        public static final int activities=0x7f050008;
        public static final int add_tag_button=0x7f050017;
        public static final int button_add_item=0x7f05000d;
        public static final int cancel=0x7f050002;
        public static final int contents=0x7f05001a;
        public static final int edittext=0x7f050001;
        public static final int edittext_add_item=0x7f05000c;
        public static final int image=0x7f05000e;
        public static final int image_URI=0x7f05000f;
        public static final int latitude=0x7f050004;
        public static final int list_items=0x7f05000b;
        public static final int listempty=0x7f050007;
        public static final int locations=0x7f050006;
        public static final int longitude=0x7f050005;
        public static final int name=0x7f050010;
        public static final int new_content=0x7f050016;
        public static final int new_tag=0x7f050015;
        public static final int ok=0x7f050003;
        public static final int spinner_listfilter=0x7f05000a;
        public static final int tag_content=0x7f050012;
        public static final int tag_filter=0x7f050018;
        public static final int tag_tag=0x7f050011;
        public static final int tag_uri_1=0x7f050013;
        public static final int tag_uri_2=0x7f050014;
        public static final int tags=0x7f050019;
        public static final int text=0x7f050000;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int input_box=0x7f030001;
        public static final int location_row=0x7f030002;
        public static final int locations=0x7f030003;
        public static final int main=0x7f030004;
        public static final int shopping=0x7f030005;
        public static final int shopping_item_row=0x7f030006;
        public static final int tag_row=0x7f030007;
        public static final int tags=0x7f030008;
    }
    public static final class string {
        public static final int about_openintents=0x7f040002;
        public static final int about_openintents_text=0x7f040003;
        public static final int add=0x7f04000b;
        public static final int add_current_location=0x7f040005;
        public static final int add_tag=0x7f04000c;
        public static final int app_name=0x7f040000;
        public static final int ask_new_list=0x7f040012;
        public static final int cancel=0x7f040016;
        public static final int clean_up_list=0x7f040010;
        public static final int confirm_delete_list=0x7f040014;
        public static final int default_tag=0x7f040001;
        public static final int delete_list=0x7f040011;
        public static final int key_return=0x7f040018;
        public static final int list_is_empty=0x7f040007;
        public static final int list_of_contents=0x7f040009;
        public static final int list_of_locations=0x7f040004;
        public static final int list_of_tags=0x7f040008;
        public static final int new_item=0x7f04000e;
        public static final int new_list=0x7f04000f;
        public static final int no_items_marked=0x7f040013;
        public static final int no_shopping_provider=0x7f040015;
        public static final int ok=0x7f040017;
        public static final int select=0x7f04000a;
        public static final int shopping_list=0x7f04000d;
        public static final int test=0x7f040019;
        public static final int view_location=0x7f040006;
    }
}
